Service/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from base import views
urlpatterns = [
    url(r'^admin/', admin.site.urls, name='superuser_admin'),
    url(r'^', include('base.urls')),
    url(r'^$',views.get_form, name='index'),
    url(r'^admin_panel$', views.get_admin_panel, name='index_admin'),
    url(r'^admin_panel/responses', views.responses, name='responses'),
    # url(r'^processing/', include('permabots.urls_processing', namespace="permabots"))
    # url(r'^webhook', views.webhooks, name='webhook')
]

base/urls.py
from django.conf.urls import url, include

from base import views

app_name = 'base'

urlpatterns = [
    url(r'orders/$', views.OrderCreate.as_view(), name='orders'),
    url(r'get_items/$', views.ItemsView.as_view(), name='get_items'),
    url(r'answer_order/$', views.AnswerOrder.as_view(), name='answer_order'),
    url(r'responses/$', views.GetResponses.as_view(), name='get_responses'),
    url(r'get_current_order', views.GetCurrentOrder.as_view(), name='get_current_view'),
    url(r'close_order', views.close_order, name='close_order'),
    url(r'login/', views.admin_login, name='login'),
    url(r'logout', views.user_logout, name='logout')
]

base/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class City(models.Model):
    name = models.CharField(max_length=255, default='')


class UserMeta(models.Model):

    phone = models.CharField(max_length=13)
    auth_field = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return u"{} |{}".format(self.phone, self.auth_field.username)

    class Meta:
        verbose_name = u'Клиент'
        verbose_name_plural = u'Клиенты'


class Item(models.Model):
    name = models.CharField(max_length=128)

    class Meta:
        abstract = True

    def __unicode__(self):
        return u"{}".format(self.name)

    def __str__(self):
        return self.__unicode__()


class ItemType(Item):

    class Meta:
        verbose_name = 'Тип техники'
        verbose_name_plural = 'Типы техники'


class ItemBrand(Item):
    item_type = models.ForeignKey(ItemType, related_name='brands', on_delete=models.CASCADE)

    def __unicode__(self):
        return u"{} {}".format(self.item_type.name, self.name)

    class Meta:
        verbose_name = u'Марка'
        verbose_name_plural = u'Марки'


class OrderItem(Item):
    item_type = models.ForeignKey(ItemType, related_name='models', on_delete=models.CASCADE)

    def __unicode__(self):
        return u"{} {} {}".format(self.item_type, self.name)

    class Meta:
        verbose_name = u'Модель'
        verbose_name_plural = u'Модели'


class Area(models.Model):
    name = models.CharField(max_length=33)

    def __unicode__(self):
        return u"{}".format(self.name)

    def __str__(self):
        return self.__unicode__()

    class Meta:
        verbose_name = u'Район'
        verbose_name_plural = u'Районы'


class Streets(models.Model):
    area = models.ForeignKey(Area, related_name='streets', null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)

    def __unicode__(self):
        return u"{}".format(self.name)

    class Meta:
        verbose_name = u'Улица'
        verbose_name_plural = u'Улицы'


class Address(models.Model):
    city = models.ForeignKey(City, related_name='addresses', null=True, blank=True, on_delete=models.CASCADE)
    street = models.ForeignKey(Streets, related_name='addresses', on_delete=models.SET_NULL, null=True)
    house = models.CharField(max_length=128, blank=True, default='')
    room = models.CharField(max_length=12, blank=True, default='')

    def __unicode__(self):
        return u"{0} ул.{1} дом.{2} кв.{3}".format(self.city, self.street.name, self.house, self.room)


class Service(models.Model):

    name = models.CharField(max_length=256)
    address = models.ForeignKey(Address, null=True, on_delete=models.SET_NULL)
    phone = models.CharField(max_length=13)
    auth_field = models.OneToOneField(User, on_delete=models.CASCADE)
    limit = models.PositiveSmallIntegerField()
    categories = models.ManyToManyField(ItemType, related_name='services')
    area = models.ForeignKey(Area, related_name='services', null=True, blank=True, on_delete=models.SET_NULL)

    def __str(self):
        return self.__unicode__()

    def __unicode__(self):
        return u"{0}".format(self.name)

    class Meta:
        verbose_name = u'Сервисный центр'
        verbose_name_plural = u'Сервисные центры'

    @property
    def get_namefield(self):
        if self.phone:
            return self.phone
        else:
            return self.auth_field.email

    def is_service(self):
        return True

class Rating(models.Model):

    vote_for = models.ForeignKey(Service, related_name='rating', on_delete=models.CASCADE)
    vote_rate = models.PositiveSmallIntegerField()


class Courier(models.Model):
    auth_field = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=13)
    passport_number = models.CharField(max_length=11, blank=True)
    area = models.ForeignKey(Area, related_name='couriers', null=True, blank=True, on_delete=models.SET_NULL)
    categories = models.ManyToManyField(ItemType, related_name='couriers')
    is_just_corier = models.BooleanField(default=True)

    @property
    def get_namefield(self):
        if self.phone:
            return self.phone
        else:
            return self.auth_field.email

    @property
    def is_busy(self):
        return self.orders.filter(is_closed=False).exists()

    def __str__(self):
        return "{} {} |{}".format(self.auth_field.last_name, self.auth_field.first_name, self.auth_field.username)

    def is_service(self):
        return False

    class Meta:
        verbose_name_plural = u'Курьеры'
        verbose_name = u'Курьер'


class Contact(models.Model):
    name = models.CharField(max_length=64, blank=True)
    phone = models.CharField(max_length=16)

    class Meta:
        verbose_name_plural = 'Контакты'
        verbose_name = 'Контакт'


class Order(models.Model):

    item = models.ForeignKey(OrderItem, related_name='orders', null=True, on_delete=models.SET_NULL)
    case = models.TextField()
    user = models.ForeignKey(UserMeta, null=True, related_name='orders', on_delete=models.CASCADE)
    address = models.ForeignKey(Address, null=True, on_delete=models.SET_NULL)
    answered_by = models.ManyToManyField(Service, related_name='answered_orders', null=True, blank=True)
    courier = models.ForeignKey(Courier, related_name='orders', null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    is_closed = models.BooleanField(default=False)
    contact = models.ForeignKey(Contact, related_name='orders', null=True, blank=True, on_delete=models.SET_NULL)
    service = models.ForeignKey(Service, related_name='services', on_delete=models.CASCADE, null=True, blank=True)

    def __unicode__(self):
        return u"{0} - {1}".format(self.item.__str__(), self.case)


class Risk(models.Model):
    service = models.ManyToManyField(Service)
    order = models.ForeignKey(Order, related_name='risks', on_delete=models.CASCADE)
    _risk = models.PositiveSmallIntegerField(default=0)

    def get_risk(self):
        return self._risk / 100

    def set_risk(self, value):
        self._risk = value

    value = property(get_risk, set_risk)

base/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, get_object_or_404, redirect
from django.http.response import JsonResponse
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer
from rest_framework.response import Response
from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.exceptions import ValidationError

from base.models import *
from base.serializers import *

from re import sub
# Create your views here.


class OrderCreate(generics.ListCreateAPIView):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

    def get_queryset(self):
        if self.request.user:
            try:
                user_obj = Courier.objects.get(auth_field=self.request.user)
            except BaseException:
                try:
                    user_obj = Service.objects.get(auth_field=self.request.user)
                except BaseException:
                    return self.queryset.order_by('created_at')

            return self.queryset.filter(Q(address__street__area=user_obj.area) | Q(address__street__area=None) | Q(address__street__area__isnull=True),
                                           item__item_type__in=user_obj.categories.all(),is_closed=False)
        return self.queryset


    def create(self, request, *args, **kwargs):

        serializer = self.get_serializer(data=request.data)

        serializer.is_valid(raise_exception=True)

        error = ''

        if request.POST.get('item_type') == u'Тип':
            error = error + ' Укажите тип.'

        if not request.POST.get('phone'):
            error += 'Укажите телефон'

        if error:
            messages.error(self.request._request, error)
            return redirect('index')

        try:
            self.perform_create(serializer)
            messages.success(self.request._request, 'Заявка успешно создана')

        except ValidationError as e:
            messages.error(self.request._request, 'Что-то пошло не так')

        return redirect('index')

    def perform_create(self, serializer):
        (street, house) = (self.request.POST.get('street'),
                           self.request.POST.get('house'),)

        if not street or not house:
            print('Одно из полей адреса пустое')
            raise ValidationError(u'Одно из полей адреса пустое')

        (street, street_is_created) = Streets.objects.get_or_create(name=street)
        try:
            (address, address_is_created) = Address.objects.get_or_create(
                street=street,
                house=self.request.POST['house'],
            )
        except BaseException as e:
            print(u'Что-то пошло не так при создании адреса', str(e))
            raise ValidationError(u'Что-то пошло не так при создании адреса')

        try:
            (item_type, created) = ItemType.objects.get_or_create(name=self.request.POST.get('item_type'))
            (item_model, created) = OrderItem.objects.get_or_create(name=self.request.POST.get('item_model'),
                                                                   item_type=item_type)
        except BaseException as e:
            print(u'Что-то пошло не так при создании сущности', str(e))
            raise ValidationError(u'Что-то пошло не так при создании сущности')

        if self.request.user and self.request.user.is_authenticated:
            user = UserMeta.objects.get_or_create(auth_field=self.request.user)[0]
        else:
            user = None

        (contact, created) = Contact.objects.get_or_create(phone=self.request.POST.get('phone'))
        if self.request.POST.get('name'):
            contact.name = self.request.POST.get('name')
            contact.save()

        serializer.save(user=user, address=address, item=item_model)


class AnswerOrder(APIView):

    def post(self, request):
        if not request.user is None and request.user.is_authenticated:
            try:
                identity = Service.objects.get(auth_field=request.user)
            except Service.DoesNotExist:
                try:
                    identity = Courier.objects.get(auth_field=request.user)
                except Courier.DoesNotExist:
                    identity = None

            if identity:
                order = Order.objects.get(pk=request.POST['id'])
                if isinstance(identity, Service):

                    if identity not in order.answered_by.all():
                        order.answered_by.add(identity)
                        order.save()
                        serializer = OrderSerializer(order)
                        return Response(serializer.data)

                    else:
                        return Response({"error": u"Вы уже ответили на эту заявку"})
                elif isinstance(identity, Courier):
                    if order.courier:
                        return Response({"error":"У заявки уже есть курьер"})
                    order.courier = identity
                    order.save()
                    serializer = OrderSerializer(order)
                    return Response(serializer.data)
            else:
                return Response({"error": u"Вы не найдены в системе, пожалуйста обратитесь в поддержку"})

        else:
            return Response({"error": u"Пожалуйста, войдите в систему"})


class GetResponses(generics.ListAPIView):
    serializer_class = OrderSerializer

    def get_queryset(self):
        if self.request.user:
            try:
                user_obj = Service.objects.get(auth_field=self.request.user)
            except BaseException:
                try:
                    user_obj = Courier.objects.get(auth_field=self.request.user)
                except BaseException:
                    return Order.objects.filter()

            if isinstance(user_obj, Courier):
                return Order.objects.filter(courier=user_obj)

            elif isinstance(user_obj, Service):
                return Order.objects.filter(answered_by__in=user_obj)

        return Order.objects.filter()


class GetCurrentOrder(generics.RetrieveAPIView):
    serializer_class = OrderSerializer
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]

    def get_object(self):
        try:
            courier = Courier.objects.get(auth_field=self.request.user)
            return Order.objects.filter(courier=courier, is_closed=False).order_by('created_at').last()
        except BaseException:
            try:
                service = Service.objects.get(auth_field=self.request.user)
                return Order.objects.filter(service=courier, is_closed=False).order_by('created_at').last()
            except BaseException:
                return None

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        if not instance:

           return Response({}, template_name='base/current_order.html', content_type='application/json')

        return Response({'order': instance}, template_name='base/current_order.html')


class ItemsView(generics.ListAPIView):
    serializer_class = AllItemSerializer
    queryset = ItemType.objects.all()



def close_order(request):
    if request.POST and 'id' in request.POST:
        try:
            order = Order.objects.get(pk=request.POST.get('id'))
            order.is_closed = True
            order.save()
            return JsonResponse({"success": 1})

        except BaseException:
            pass

    return JsonResponse({"error": u"Что-то пошло не так при закрытии заказа, "
                                     u"пожалуйста, попробуйте снова или обратитесь в службу поддержки"})


def responses(request):
    return render(request, 'base/responses.html')


def get_form(requset):
    return render(requset, 'landing/index.html')


def get_admin_panel(request):
    if request.user:
        if request.user.is_authenticated:

            try:
                courier = Courier.objects.get(auth_field=request.user)
            except BaseException:
		try:
		    courier = Service.objects.get(auth_field=request.user)
		except BaseException:

	            return render(request, 'base/login.html')

            return render(request, 'base/starter.html', {'courier':courier})

    context = {}
    if request.session.get('login_error'):
        context['error'] = request.session.get('login_error')
        del request.session['login_error']

    return render(request, 'base/login.html', context)


def admin_login(request):
    username = request.POST.get('username')
    password = request.POST.get('pass')

    if username and password:
        user = authenticate(username=username,password=password)
	
        if user:
            login(request, user)
            return redirect('index_admin')

        else:
            request.session['login_error'] = 'Пользователь не найден'
            return redirect('index_admin')

    request.session['login_error'] = 'Ошибка в передаче данных, пожалуйста обратитесь в поддержку'
    return redirect('index_admin')


def user_logout(request):
    return_page = request.user.is_superuser and '/admin/' or 'index_admin'
    logout(request)
    return redirect(return_page)

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Starter</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="/static/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="/static/bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect. -->
  <link rel="stylesheet" href="/static/dist/css/skins/skin-blue.min.css">

  <link rel="stylesheet" href="{%  static 'bower_components/datatables.net-bs/css/dataTables.bootstrap.css' %}">
  <link rel="stylesheet" href="{%  static 'css/admin_panel.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>P</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Admin</b>Page</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
{#          <!-- Messages: style can be found in dropdown.less-->#}
{#          <li class="dropdown messages-menu">#}
{#            <!-- Menu toggle button -->#}
{#            <a href="#" class="dropdown-toggle" data-toggle="dropdown">#}
{#              <i class="fa fa-envelope-o"></i>#}
{#              <span class="label label-success">4</span>#}
{#            </a>#}
{#            <ul class="dropdown-menu">#}
{#              <li class="header">You have 4 messages</li>#}
{#              <li>#}
{#                <!-- inner menu: contains the messages -->#}
{#                <ul class="menu">#}
{#                  <li><!-- start message -->#}
{#                    <a href="#">#}
{#                      <div class="pull-left">#}
{#                        <!-- User Image -->#}
{#                        <img src="/static/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">#}
{#                      </div>#}
{#                      <!-- Message title and timestamp -->#}
{#                      <h4>#}
{#                        Support Team#}
{#                        <small><i class="fa fa-clock-o"></i> 5 mins</small>#}
{#                      </h4>#}
{#                      <!-- The message -->#}
{#                      <p>Why not buy a new awesome theme?</p>#}
{#                    </a>#}
{#                  </li>#}
{#                  <!-- end message -->#}
{#                </ul>#}
{#                <!-- /.menu -->#}
{#              </li>#}
{#              <li class="footer"><a href="#">See All Messages</a></li>#}
{#            </ul>#}
{#          </li>#}
{#          <!-- /.messages-menu -->#}
{##}
{#          <!-- Notifications Menu -->#}
{#          <li class="dropdown notifications-menu">#}
{#            <!-- Menu toggle button -->#}
{#            <a href="#" class="dropdown-toggle" data-toggle="dropdown">#}
{#              <i class="fa fa-bell-o"></i>#}
{#              <span class="label label-warning">10</span>#}
{#            </a>#}
{#            <ul class="dropdown-menu">#}
{#              <li class="header">You have 10 notifications</li>#}
{#              <li>#}
{#                <!-- Inner Menu: contains the notifications -->#}
{#                <ul class="menu">#}
{#                  <li><!-- start notification -->#}
{#                    <a href="#">#}
{#                      <i class="fa fa-users text-aqua"></i> 5 new members joined today#}
{#                    </a>#}
{#                  </li>#}
{#                  <!-- end notification -->#}
{#                </ul>#}
{#              </li>#}
{#              <li class="footer"><a href="#">View all</a></li>#}
{#            </ul>#}
{#          </li>#}
{#          <!-- Tasks Menu -->#}
{#          <li class="dropdown tasks-menu">#}
{#            <!-- Menu Toggle Button -->#}
{#            <a href="#" class="dropdown-toggle" data-toggle="dropdown">#}
{#              <i class="fa fa-flag-o"></i>#}
{#              <span class="label label-danger">9</span>#}
{#            </a>#}
{#            <ul class="dropdown-menu">#}
{#              <li class="header">You have 9 tasks</li>#}
{#              <li>#}
{#                <!-- Inner menu: contains the tasks -->#}
{#                <ul class="menu">#}
{#                  <li><!-- Task item -->#}
{#                    <a href="#">#}
{#                      <!-- Task title and progress text -->#}
{#                      <h3>#}
{#                        Design some buttons#}
{#                        <small class="pull-right">20%</small>#}
{#                      </h3>#}
{#                      <!-- The progress bar -->#}
{#                      <div class="progress xs">#}
{#                        <!-- Change the css width attribute to simulate progress -->#}
{#                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"#}
{#                             aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">#}
{#                          <span class="sr-only">20% Complete</span>#}
{#                        </div>#}
{#                      </div>#}
{#                    </a>#}
{#                  </li>#}
{#                  <!-- end task item -->#}
{#                </ul>#}
{#              </li>#}
{#              <li class="footer">#}
{#                <a href="#">View all tasks</a>#}
{#              </li>#}
{#            </ul>#}
{#          </li>#}
          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
{#              <img src="/static/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">#}
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs">
                 {{ courier.get_namefield }}
              </span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
{#                <img src="/static/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">#}

                <p>
                {{ courier.get_namefield }}

                {% if courier.is_just_courier %}
                    Курьер
                {% elif courier.is_service %}
                    СЦ
                {% else %}
                    Мастер
                {% endif %}
                  <small>Member since {{ courier.auth_field.date_joined }}</small>
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="col-xs-12">
                  <a href="{% url 'base:logout' %}" id="logout" class="col-xs-12 btn btn-default btn-flat">Выйти</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MENU</li>
        <!-- Optionally, you can add icons to the links -->
        <li class="active"><a href="{% url 'index_admin' %}"><i class="fa fa-link"></i> <span>Все заказы</span></a></li>
        <li><a href="{% url 'responses' %}"><i class="fa fa-link"></i> <span>Ответы на заказы</span></a></li>
        <li class="treeview">
          <a href="#"><i class="fa fa-link"></i> <span>Адреса</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
        </li>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
{% block 'page_title' %}{% endblock %}
      </h1>

    </section>

    <!-- Main content -->
    <section class="content container-fluid">
        {% block 'content' %}
        {% endblock %}
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
  immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 3 -->
<script src="/static/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- AdminLTE App -->
<script src="/static/dist/js/adminlte.min.js"></script>

<script src="{% static 'js/admin_panel.js' %}"></script>
<script src="{% static 'js/js.cookie.js' %}"></script>

<script src="{% static 'bower_components/datatables.net/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'bower_components/datatables.net-bs/js/dataTables.bootstrap.js' %}"></script>

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->
</body>
</html>

base/templates/base/current_order.html
{% if order %}
    <div class="box-header with-border">
        <div class="box-title">
            <h3>Текущая заявка: {{ order.item }}</h3>
        </div>
    </div>
    <div class="box-body">

        <div class="col-xs-12 current_order-body" data-orderID="{{ order.pk }}">
            <div class="row">
                <div class="col-xs-4">
                    <div class="row">
                        <h4><strong>Адрес:</strong></h4>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="row">
                                <strong>Город:</strong>
                            </div>
                            <div class="row">
                                {{ order.address.city }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="row">
                                <strong>Улица:</strong>
                            </div>
                            <div class="row">
                                {{ order.address.street }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="row">
                                <strong>Дом:</strong>
                            </div>
                            <div class="row">
                                {{ order.address.house }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="row">
                                <strong>Квартира:</strong>
                            </div>
                            <div class="row">
                                {{ order.address.room }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-4">
                    <div class="row">
                        <h4><strong>Описание проблемы:</strong></h4>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            {{ order.case }}
                        </div>
                    </div>
                </div>
                <div class="col-xs-4">
                    <div class="row">
                        <h4><strong>Контакты:</strong></h4>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="row">
                                <div class="col-xs-12">
                                    {{ order.contact.phone }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    {{ order.contact.name }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer">
    <div class="box-tools">
            <button class="btn btn-danger col-xs-12" id="close_order" data-id="{{ order.pk }}">Закрыть заявку</button>
        </div>
    </div>
{% else %}
    {'error':"У вас нет заявки"}
{% endif %}