Service/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from base import views
urlpatterns = [
    url(r'^admin/', admin.site.urls, name='superuser_admin'),
    url(r'^', include('base.urls')),
    url(r'^$',views.get_form, name='index'),
    url(r'^admin_panel$', views.get_admin_panel, name='index_admin'),
    url(r'^admin_panel/responses', views.responses, name='responses'),
    # url(r'^processing/', include('permabots.urls_processing', namespace="permabots"))
    # url(r'^webhook', views.webhooks, name='webhook')
]

base/urls.py
from django.conf.urls import url, include

from base import views

app_name = 'base'

urlpatterns = [
    url(r'orders/$', views.OrderCreate.as_view(), name='orders'),
    url(r'get_items/$', views.ItemsView.as_view(), name='get_items'),
    url(r'answer_order/$', views.AnswerOrder.as_view(), name='answer_order'),
    url(r'responses/$', views.GetResponses.as_view(), name='get_responses'),
    url(r'get_current_order', views.GetCurrentOrder.as_view(), name='get_current_view'),
    url(r'close_order', views.close_order, name='close_order'),
    url(r'login/', views.admin_login, name='login'),
    url(r'logout', views.user_logout, name='logout')
]

base/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class City(models.Model):
    name = models.CharField(max_length=255, default='')


class UserMeta(models.Model):

    phone = models.CharField(max_length=13)
    auth_field = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return u"{} |{}".format(self.phone, self.auth_field.username)

    class Meta:
        verbose_name = u'Клиент'
        verbose_name_plural = u'Клиенты'


class Item(models.Model):
    name = models.CharField(max_length=128)

    class Meta:
        abstract = True

    def __unicode__(self):
        return u"{}".format(self.name)

    def __str__(self):
        return self.__unicode__()


class ItemType(Item):

    class Meta:
        verbose_name = 'Тип техники'
        verbose_name_plural = 'Типы техники'


class ItemBrand(Item):
    item_type = models.ForeignKey(ItemType, related_name='brands', on_delete=models.CASCADE)

    def __unicode__(self):
        return u"{} {}".format(self.item_type.name, self.name)

    class Meta:
        verbose_name = u'Марка'
        verbose_name_plural = u'Марки'


class OrderItem(Item):
    item_type = models.ForeignKey(ItemType, related_name='models', on_delete=models.CASCADE)

    def __unicode__(self):
        return u"{} {} {}".format(self.item_type, self.name)

    class Meta:
        verbose_name = u'Модель'
        verbose_name_plural = u'Модели'


class Area(models.Model):
    name = models.CharField(max_length=33)

    def __unicode__(self):
        return u"{}".format(self.name)

    def __str__(self):
        return self.__unicode__()

    class Meta:
        verbose_name = u'Район'
        verbose_name_plural = u'Районы'


class Streets(models.Model):
    area = models.ForeignKey(Area, related_name='streets', null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)

    def __unicode__(self):
        return u"{}".format(self.name)

    class Meta:
        verbose_name = u'Улица'
        verbose_name_plural = u'Улицы'


class Address(models.Model):
    city = models.ForeignKey(City, related_name='addresses', null=True, blank=True, on_delete=models.CASCADE)
    street = models.ForeignKey(Streets, related_name='addresses', on_delete=models.SET_NULL, null=True)
    house = models.CharField(max_length=128, blank=True, default='')
    room = models.CharField(max_length=12, blank=True, default='')

    def __unicode__(self):
        return u"{0} ул.{1} дом.{2} кв.{3}".format(self.city, self.street.name, self.house, self.room)


class Service(models.Model):

    name = models.CharField(max_length=256)
    address = models.ForeignKey(Address, null=True, on_delete=models.SET_NULL)
    phone = models.CharField(max_length=13)
    auth_field = models.OneToOneField(User, on_delete=models.CASCADE)
    limit = models.PositiveSmallIntegerField()
    categories = models.ManyToManyField(ItemType, related_name='services')
    area = models.ForeignKey(Area, related_name='services', null=True, blank=True, on_delete=models.SET_NULL)

    def __str(self):
        return self.__unicode__()

    def __unicode__(self):
        return u"{0}".format(self.name)

    class Meta:
        verbose_name = u'Сервисный центр'
        verbose_name_plural = u'Сервисные центры'

    @property
    def get_namefield(self):
        if self.phone:
            return self.phone
        else:
            return self.auth_field.email

    def is_service(self):
        return True

class Rating(models.Model):

    vote_for = models.ForeignKey(Service, related_name='rating', on_delete=models.CASCADE)
    vote_rate = models.PositiveSmallIntegerField()


class Courier(models.Model):
    auth_field = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=13)
    passport_number = models.CharField(max_length=11, blank=True)
    area = models.ForeignKey(Area, related_name='couriers', null=True, blank=True, on_delete=models.SET_NULL)
    categories = models.ManyToManyField(ItemType, related_name='couriers')
    is_just_corier = models.BooleanField(default=True)

    @property
    def get_namefield(self):
        if self.phone:
            return self.phone
        else:
            return self.auth_field.email

    @property
    def is_busy(self):
        return self.orders.filter(is_closed=False).exists()

    def __str__(self):
        return "{} {} |{}".format(self.auth_field.last_name, self.auth_field.first_name, self.auth_field.username)

    def is_service(self):
        return False

    class Meta:
        verbose_name_plural = u'Курьеры'
        verbose_name = u'Курьер'


class Contact(models.Model):
    name = models.CharField(max_length=64, blank=True)
    phone = models.CharField(max_length=16)

    class Meta:
        verbose_name_plural = 'Контакты'
        verbose_name = 'Контакт'


class Order(models.Model):

    item = models.ForeignKey(OrderItem, related_name='orders', null=True, on_delete=models.SET_NULL)
    case = models.TextField()
    user = models.ForeignKey(UserMeta, null=True, related_name='orders', on_delete=models.CASCADE)
    address = models.ForeignKey(Address, null=True, on_delete=models.SET_NULL)
    answered_by = models.ManyToManyField(Service, related_name='answered_orders', null=True, blank=True)
    courier = models.ForeignKey(Courier, related_name='orders', null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    is_closed = models.BooleanField(default=False)
    contact = models.ForeignKey(Contact, related_name='orders', null=True, blank=True, on_delete=models.SET_NULL)
    service = models.ForeignKey(Service, related_name='services', on_delete=models.CASCADE, null=True, blank=True)

    def __unicode__(self):
        return u"{0} - {1}".format(self.item.__str__(), self.case)


class Risk(models.Model):
    service = models.ManyToManyField(Service)
    order = models.ForeignKey(Order, related_name='risks', on_delete=models.CASCADE)
    _risk = models.PositiveSmallIntegerField(default=0)

    def get_risk(self):
        return self._risk / 100

    def set_risk(self, value):
        self._risk = value

    value = property(get_risk, set_risk)

base/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, get_object_or_404, redirect
from django.http.response import JsonResponse
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer
from rest_framework.response import Response
from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.exceptions import ValidationError

from base.models import *
from base.serializers import *

from re import sub
# Create your views here.


class OrderCreate(generics.ListCreateAPIView):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

    def get_queryset(self):
        if self.request.user:
            try:
                user_obj = Courier.objects.get(auth_field=self.request.user)
            except BaseException:
                try:
                    user_obj = Service.objects.get(auth_field=self.request.user)
                except BaseException:
                    return self.queryset.order_by('created_at')

            return self.queryset.filter(Q(address__street__area=user_obj.area) | Q(address__street__area=None) | Q(address__street__area__isnull=True),
                                           item__item_type__in=user_obj.categories.all(),is_closed=False)
        return self.queryset


    def create(self, request, *args, **kwargs):

        serializer = self.get_serializer(data=request.data)

        serializer.is_valid(raise_exception=True)

        error = ''

        if request.POST.get('item_type') == u'Тип':
            error = error + ' Укажите тип.'

        if not request.POST.get('phone'):
            error += 'Укажите телефон'

        if error:
            messages.error(self.request._request, error)
            return redirect('index')

        try:
            self.perform_create(serializer)
            messages.success(self.request._request, 'Заявка успешно создана')

        except ValidationError as e:
            messages.error(self.request._request, 'Что-то пошло не так')

        return redirect('index')

    def perform_create(self, serializer):
        (street, house) = (self.request.POST.get('street'),
                           self.request.POST.get('house'),)

        if not street or not house:
            print('Одно из полей адреса пустое')
            raise ValidationError(u'Одно из полей адреса пустое')

        (street, street_is_created) = Streets.objects.get_or_create(name=street)
        try:
            (address, address_is_created) = Address.objects.get_or_create(
                street=street,
                house=self.request.POST['house'],
            )
        except BaseException as e:
            print(u'Что-то пошло не так при создании адреса', str(e))
            raise ValidationError(u'Что-то пошло не так при создании адреса')

        try:
            (item_type, created) = ItemType.objects.get_or_create(name=self.request.POST.get('item_type'))
            (item_model, created) = OrderItem.objects.get_or_create(name=self.request.POST.get('item_model'),
                                                                   item_type=item_type)
        except BaseException as e:
            print(u'Что-то пошло не так при создании сущности', str(e))
            raise ValidationError(u'Что-то пошло не так при создании сущности')

        if self.request.user and self.request.user.is_authenticated:
            user = UserMeta.objects.get_or_create(auth_field=self.request.user)[0]
        else:
            user = None

        (contact, created) = Contact.objects.get_or_create(phone=self.request.POST.get('phone'))
        if self.request.POST.get('name'):
            contact.name = self.request.POST.get('name')
            contact.save()

        serializer.save(user=user, address=address, item=item_model)


class AnswerOrder(APIView):

    def post(self, request):
        if not request.user is None and request.user.is_authenticated:
            try:
                identity = Service.objects.get(auth_field=request.user)
            except Service.DoesNotExist:
                try:
                    identity = Courier.objects.get(auth_field=request.user)
                except Courier.DoesNotExist:
                    identity = None

            if identity:
                order = Order.objects.get(pk=request.POST['id'])
                if isinstance(identity, Service):

                    if identity not in order.answered_by.all():
                        order.answered_by.add(identity)
                        order.save()
                        serializer = OrderSerializer(order)
                        return Response(serializer.data)

                    else:
                        return Response({"error": u"Вы уже ответили на эту заявку"})
                elif isinstance(identity, Courier):
                    if order.courier:
                        return Response({"error":"У заявки уже есть курьер"})
                    order.courier = identity
                    order.save()
                    serializer = OrderSerializer(order)
                    return Response(serializer.data)
            else:
                return Response({"error": u"Вы не найдены в системе, пожалуйста обратитесь в поддержку"})

        else:
            return Response({"error": u"Пожалуйста, войдите в систему"})


class GetResponses(generics.ListAPIView):
    serializer_class = OrderSerializer

    def get_queryset(self):
        if self.request.user:
            try:
                user_obj = Service.objects.get(auth_field=self.request.user)
            except BaseException:
                try:
                    user_obj = Courier.objects.get(auth_field=self.request.user)
                except BaseException:
                    return Order.objects.filter()

            if isinstance(user_obj, Courier):
                return Order.objects.filter(courier=user_obj)

            elif isinstance(user_obj, Service):
                return Order.objects.filter(answered_by__in=user_obj)

        return Order.objects.filter()


class GetCurrentOrder(generics.RetrieveAPIView):
    serializer_class = OrderSerializer
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]

    def get_object(self):
        try:
            courier = Courier.objects.get(auth_field=self.request.user)
            return Order.objects.filter(courier=courier, is_closed=False).order_by('created_at').last()
        except BaseException:
            try:
                service = Service.objects.get(auth_field=self.request.user)
                return Order.objects.filter(service=courier, is_closed=False).order_by('created_at').last()
            except BaseException:
                return None

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        if not instance:

           return Response({}, template_name='base/current_order.html', content_type='application/json')

        return Response({'order': instance}, template_name='base/current_order.html')


class ItemsView(generics.ListAPIView):
    serializer_class = AllItemSerializer
    queryset = ItemType.objects.all()



def close_order(request):
    if request.POST and 'id' in request.POST:
        try:
            order = Order.objects.get(pk=request.POST.get('id'))
            order.is_closed = True
            order.save()
            return JsonResponse({"success": 1})

        except BaseException:
            pass

    return JsonResponse({"error": u"Что-то пошло не так при закрытии заказа, "
                                     u"пожалуйста, попробуйте снова или обратитесь в службу поддержки"})


def responses(request):
    return render(request, 'base/responses.html')


def get_form(requset):
    return render(requset, 'landing/index.html')


def get_admin_panel(request):
    if request.user:
        if request.user.is_authenticated:

            try:
                courier = Courier.objects.get(auth_field=request.user)
            except BaseException:
		try:
		    courier = Service.objects.get(auth_field=request.user)
		except BaseException:

	            return render(request, 'base/login.html')

            return render(request, 'base/starter.html', {'courier':courier})

    context = {}
    if request.session.get('login_error'):
        context['error'] = request.session.get('login_error')
        del request.session['login_error']

    return render(request, 'base/login.html', context)


def admin_login(request):
    username = request.POST.get('username')
    password = request.POST.get('pass')

    if username and password:
        user = authenticate(username=username,password=password)
	
        if user:
            login(request, user)
            return redirect('index_admin')

        else:
            request.session['login_error'] = 'Пользователь не найден'
            return redirect('index_admin')

    request.session['login_error'] = 'Ошибка в передаче данных, пожалуйста обратитесь в поддержку'
    return redirect('index_admin')


def user_logout(request):
    return_page = request.user.is_superuser and '/admin/' or 'index_admin'
    logout(request)
    return redirect(return_page)

base/templates/landing/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title>LOGOTYPE SERVICE | Выездной ремонт вашей техники</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	
	<link rel="shortcut icon" href="static/assets/images/favicon.png" type="image/png">
	<!-- Css -->
	<link rel="stylesheet" href="static/assets/css/style.css">
	<!-- ebd Css -->
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- end Font Awesome -->
	<!-- Nice Select -->
	<link rel="stylesheet" href="static/assets/css/nice-select.css">
	<!-- end Nice Select -->
	<!-- Swiper -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.2.2/css/swiper.min.css">
	<!-- end Swiper -->
	<!-- FancyBox -->
	<link rel="stylesheet" href="static/assets/css/jquery.fancybox.min.css">
	<!-- end FancyBox -->
    <link rel="stylesheet" href="/static/css/bootstrap.css">

</head>
<body>

	<!-- Mobile menu -->
	<div class="m__menu__">
		<ul class="m__menu__nav">
			<li><a class="ancor__M" href="#advantages">ПРЕИМУЩЕСТВА</a></li>
			<li><a class="ancor__M" href="#about">КАК МЫ РАБОТАЕМ</a></li>
			<li><a class="ancor__M" href="#contact">КОНТАКТЫ</a></li>
			<li><a href="#">ПРАЙС</a></li>
			<li><a href="#" class="close">Закрыть</a></li>
		</ul>
	</div>
	<!-- end Mobile menu -->

	<!-- Header -->
	<header>
		<div class="wrap">
			<ul class="nav">
				<li><a href="#advantages" class="ancor__">ПРЕИМУЩЕСТВА</a></li>
				<li><a href="#about" class="ancor__">КАК МЫ РАБОТАЕМ</a></li>
			</ul>
			<div class="logo">
				<a href="index.html">
					<img src="static/assets/images/logo.png" alt="logo">
				</a>
			</div>
			<ul class="nav">
				<li><a href="#contact" class="ancor__">КОНТАКТЫ</a></li>
				<li><a href="#">ПРАЙС</a></li>
			</ul>
			<ul class="socials">
				<li><a href="#"><i class="fa fa-vk" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-paper-plane" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
			</ul>
			<a href="#" class="Toogle_menu"><i class="fa fa-bars" aria-hidden="true"></i></a>
		</div>
	</header>
	<!-- end Header -->

	<!-- Home -->
	<div class="home">
		<div class="particles" id="particles">
			
		</div>
		<div class="wrap">
			<div class="home_contect">
				<h1>LOGOTYPE SERVICE <span>Выездной ремонт вашей техники</span></h1>
				<p>Ремонт телефонов, ноутбуков, стиральных машин и прочей бытовой техники и электроники.</p>
				<p>Оставьте заявку и к вам приедет мастер, сделает диагностику и починит устройство.</p>
				<p>Если ремонт на месте не возможен, то мы доставим устройство в нужный сервисный центр</p>
				<div class="order__home">
					<a href="https://www.youtube.com/watch?v=G7NSaXIEL4Y" data-fancybox class="more__order_green">Смотреть видео</a>
					<a href="#" class="more__order">Узнать больше</a>
				</div>
			</div>
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
			<div class="form_content">
                {{ message }}
				<form method="post" action="{% url 'base:orders' %}">>
					<div class="el_">
						<select name="item_type" required>
							<option value="Тип">Тип</option>
						</select>
					</div>
					<div class="el_">
						<input type="text" name="item_model" placeholder="Модель" required>
					</div>
					<div class="el_">
						<input type="text" name="phone" placeholder="Номер телефона" required>
					</div>
					<div class="el_">
						<label>
							<input type="text" name="street" placeholder="Улица" required>
							<input type="text" name="house" placeholder="Дом" required>
						</label>
					</div>
					<div class="el_">
						<textarea name="case" placeholder="Опишите проблему"></textarea>
					</div>
					<div class="el_">
						<button type="submit">Отправить заявку</button>
					</div>
					<div class="el_">
						<a href="tel:+73852751875"><i class="fa fa-phone" aria-hidden="true"></i> +7 (3852) 75-18-75</a>
					</div>
                    {% csrf_token %}
				</form>
			</div>
		</div>
	</div>
	<!-- end Home -->

	<!-- Advantages -->
	<div class="advantages" id="advantages">
		<div class="particles" id="particles_2">
			
		</div>
		<div class="wrap">
			<div class="title__section">
				<h2>ПРЕИМУЩЕСТВА</h2>
				<p>Приятно удивим вас ...</p>
			</div>
			<div class="advantages__items">
				<div class="advantages__item">
					<div class="item__ico">
						<img src="static/assets/images/adw-cio-1.png" alt="adw-cio">
					</div>
					<h4>ВЫЕЗД В ЛЮБУЮ ТОЧКУ</h4>
					<p>Мастер приедет в удобное вам место и назовет цену ремонта.</p>
				</div>
				<div class="advantages__item">
					<div class="item__ico">
						<img src="static/assets/images/adw-cio-2.png" alt="adw-cio">
					</div>
					<h4>МАСТЕРА С РУКАМИ ИЗ ПЛЕЧ</h4>
					<p>Наши специалисты имеют высокую квалификацию и постоянно совершенствуются.</p>
				</div>
				<div class="advantages__item">
					<div class="item__ico">
						<img src="static/assets/images/adw-cio-3.png" alt="adw-cio">
					</div>
					<h4>НАДЕЖНОСТЬ</h4>
					<p>Мы работаем с проверенными сервисными центрами, которые предоставляют гарантию.</p>
				</div>
				<div class="advantages__item">
					<div class="item__ico">
						<img src="static/assets/images/adw-cio-4.png" alt="adw-cio">
					</div>
					<h4>БЫСТРЫЙ РЕМОНТ</h4>
					<p>Ремонт проходит в максимально быстрые сроки.</p>
				</div>
				<div class="advantages__item">
					<div class="item__ico">
						<img src="static/assets/images/adw-cio-5.png" alt="adw-cio">
					</div>
					<h4>ПРОЗРАЧНОСТЬ</h4>
					<p>В любой момент вы можете узнать где и на какой стадии находится ваше устройство через личный кабинет или Telegram.</p>
				</div>
				<div class="advantages__item">
					<div class="item__ico">
						<img src="static/assets/images/adw-cio-6.png" alt="adw-cio">
					</div>
					<h4>ПОДМЕННОЕ УСТРОЙСТВО</h4>
					<p>Если ваш смартфон или ноутбук нуждается в стационарном ремонте, то на это время мы предоставим вам подменное устройство.</p>
				</div>
			</div>
		</div>
	</div>
	<!-- end Advantages -->

	<!-- About -->
	<div class="about" id="about">
		<div class="wrap">
			<div class="title__section">
				<h2>КАК МЫ РАБОТАЕМ</h2>
				<p>Упростим вам жизнь...</p>
			</div>
			<div class="about__items">
				<div class="about_item">
					<div class="ite__s">
						<p>
							<span class="visible">ОСТАВЬТЕ ЗАЯВКУ МАСТЕР СВЯЖЕТСЯ С ВАМИ</span>
							<span class="hover">Вы заполняете заявку и в ближайшее время Вам звонит мастер для уточнения данных.</span>
						</p>
						<div class="ico">
							<i class="fa fa-television" aria-hidden="true"></i>
						</div>
					</div>
					<div class="ite__s">
						<p>
							<span class="visible">МАСТЕР ОЦЕНИТ ПРОБЛЕМУ НА МЕСТЕ И НАЗОВЕТ ЦЕНУ</span>
							<span class="hover">В назначенном месте он оценит поломку и назовет цену, которую вы так же можете узнать в прайс-листе.</span>
						</p>
						<div class="ico">
							<i class="fa fa-map-o" aria-hidden="true"></i>
						</div>
					</div>
					<div class="ite__s">
						<p>
							<span class="visible">УСТРАНЕНИЕ НЕСЕРЬЕЗНЫХ ПОЛОМОК НА МЕСТЕ</span>
							<span class="hover">Если поломка не серьезная, то он устранит её на месте.</span>
						</p>
						<div class="ico">
							<i class="fa fa-cogs" aria-hidden="true"></i>
						</div>
					</div>
				</div>
				<div class="about_item">
					<div class="ite__s">
						
						<div class="ico">
							<i class="fa fa-phone" aria-hidden="true"></i>
						</div>
						<p>
							<span class="visible">ПРИ СЕРЬЕЗНЫХ ПОЛОМКАХ - НАПРАВИМ В СЕРВИСНЫЙ ЦЕНТР</span>
							<span class="hover">Если это невозможно, то мы направим ваше устройство в наиболее подходящий сервисный центр.</span>
						</p>
					</div>
					<div class="ite__s">
						
						<div class="ico">
							<i class="fa fa-flag-o" aria-hidden="true"></i>
						</div>
						<p>
							<span class="visible">ПОЛУЧИТЕ ВРЕМЕННОЕ УСТРОЙСТВО ВЗАМЕН ВАШЕГО</span>
							<span class="hover">При этом вы можете получить от нас ноутбук или смартфон на замену своему на время ремонта.</span>
						</p>
					</div>
					<div class="ite__s">
						
						<div class="ico">
							<i class="fa fa-check-square-o" aria-hidden="true"></i>
						</div>
						<p>
							<span class="visible">ПОЛУЧИТЕ ВРЕМЕННОЕ УСТРОЙСТВО ВЗАМЕН ВАШЕГО</span>
							<span class="hover">По завершении ремонта мы доставим ваше устройство в удобное вам место. Оплатите заказ, когда убедитесь, что всё в порядке.</span>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end About -->

	<!-- Footer -->
	<footer id="contact">
		<div class="wrap">
			<div class="title__section">
				<h2>МЫ ГОРДИМСЯ РАБОТОЙ</h2>
				<p>С ЛУЧШИМИ КОМПАНИЯМИ</p>
			</div>
			<div class="partners__slider swiper-container">
				<div class="swiper-wrapper">
					<div class="swiper-slide partners__slider_item">
						<img src="static/assets/images/p-1.png" alt="partners__slider_item">
					</div>
					<div class="swiper-slide partners__slider_item">
						<img src="static/assets/images/p-2.png" alt="partners__slider_item">
					</div>
					<div class="swiper-slide partners__slider_item">
						<img src="static/assets/images/p-3.png" alt="partners__slider_item">
					</div>
					<div class="swiper-slide partners__slider_item">
						<img src="static/assets/images/p-2.png" alt="partners__slider_item">
					</div>
					<div class="swiper-slide partners__slider_item">
						<img src="static/assets/images/p-3.png" alt="partners__slider_item">
					</div>
				</div>
				<!-- Add Arrows -->
			    <div class="swiper-button-next"></div>
			    <div class="swiper-button-prev"></div>
			</div>
			<div class="footer__menu">
				<div class="logo">
					<a href="index.html">LOGOTYPE</a>
					<span>Все права защищены © 2018</span>
				</div>
				<div class="menu__f">
					<ul>
						<li>ЕСТЬ ВОПРОС - ПОЗВОНИ</li>
						<li><a href="tel:74952222222">+7 495 222-22-22</a></li>
					</ul>
					<ul>
						<li><a href="#">ПОЛИТИКА КОНФИДЕЦИАЛЬНОСТИ</a></li>
						<li><a href="#">СПОСОБЫ ОПЛАТЫ</a></li>
					</ul>
					<ul>
						<li><a href="#">ПАРТНЕРЫ</a></li>
						<li><a href="#">СОТРУДНИЧЕСТВО</a></li>
					</ul>
					<ul>
						<li><a href="#">НАПИШИ НАМ</a></li>
						<li><a href="#">LOGOTYPE@LOGO.RU</a></li>
					</ul>
				</div>
				<ul class="socials">
					<li><a href="#"><i class="fa fa-vk" aria-hidden="true"></i></a></li>
					<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
					<li><a href="#"><i class="fa fa-paper-plane" aria-hidden="true"></i></a></li>
					<li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
				</ul>
			</div>
		</div>
	</footer>
	<!-- end Footer -->
	







	<!-- Script -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Nice Select -->
	<script src="static/assets/js/jquery.nice-select.js"></script>
	<!-- end Nice Select -->
	<!-- Swiper -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.2.2/js/swiper.min.js"></script>
	<!-- end Swiper -->
	<!-- FancyBox -->
	<script src="static/assets/js/jquery.fancybox.min.js"></script>
	<!-- end FancyBox -->
	<!-- Particles -->
	<script src="static/assets/js/particles.min.js"></script>
	<!-- end Particles -->
	<!-- HeadHesive -->
	<script src="static/assets/js/headhesive.min.js"></script>
	<!-- end HeadHesive -->
	<script src="static/assets/js/script.js"></script>
	<!-- end Script -->
</body>
</html>